version: '3.5'

services:
  iptv-mysql:
    container_name: iptv-mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_iptv_testing
      MYSQL_USER: shehzad
      MYSQL_PASSWORD: shehzad
      MYSQL_ROOT_PASSWORD: shehzad
    networks:
      - iptv-network
    volumes:
      - iptv-data-azure:/var/lib/mysql

  iptv-spring-app:
    container_name: iptv-spring-app
    depends_on: 
      - iptv-mysql
    links:
      - iptv-mysql:iptv-mysql
    restart: always
    image: iptvregistry.azurecr.io/iptv-spring-app
    networks:
      - iptv-network
    ports:
      - 8080:8080
    environment:
      - JAR_FILE=*.jar
      - SPRING_DATASOURCE_URL=jdbc:mysql://iptv-mysql:3306/db_iptv_testing
      - SPRING_DATASOURCE_USERNAME=shehzad
      - SPRING_DATASOURCE_PASSWORD=shehzad
    volumes:
      - iptv-data-azure:/data

volumes: 
    iptv-data-azure:
        driver: azure_file
        driver_opts:
            share_name: iptvsharestorage
            storage_account_name: iptvdockerstorage

networks:
    iptv-network:
        driver: bridge